#!/usr/bin/env bash
set -euo pipefail

# Make sure workspaces are fixed and there are at least 6
gsettings set org.gnome.mutter dynamic-workspaces false
gsettings set org.gnome.desktop.wm.preferences num-workspaces 6

# Disable dock/app switching on Super+5 and Super+6
gsettings set org.gnome.shell.keybindings switch-to-application-5 "[]"
gsettings set org.gnome.shell.keybindings switch-to-application-6 "[]"

# Switch to workspace 5/6 with Super+5/6
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Super>5']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Super>6']"

# Move window to workspace 5/6 with Shift+Super+5/6
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5 "['<Shift><Super>5']"
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6 "['<Shift><Super>6']"

# Disable middle mouse paste
gsettings set org.gnome.desktop.interface gtk-enable-primary-paste false

echo "Applied settings to gnome"

